package ZealWebPage;


// Generated by Selenium IDE

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.Map;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class ZealContact {
    static WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeAll
    static void setUp() {

        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");

        driver = new ChromeDriver(options);
        driver.manage().window().setSize(new Dimension(920, 155));
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
        driver.get("https://www.zealitconsultants.com/");
    }

    @AfterAll
    static void teardown() {

        //Cleanup
        System.out.println("this needs to slow it down");
        try {
            Thread.sleep(6000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.close();
        driver.quit();
        System.out.println("after quitting");
    }

    @Test
    public void justTheFrontend() {
        // Test name: JustTheFrontend
        // Step # | name | target | value
        // 1 | open | / |
        // 2 | setWindowSize | 1920x1055 |
        driver.manage().window().setSize(new Dimension(1920, 1055));
        // 3 | click | id=name |
        driver.findElement(By.id("name"));
        // 4 | type | id=name | Tester Purpose
        driver.findElement(By.id("name")).sendKeys("Tester " + LocalDateTime.now());

    }
}





